services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: terminal-backend
    restart: always
    ports:
      - "5050:5000"
    environment:
      - FLASK_APP=presentation/app.py
      - FLASK_ENV=development
      - ALPHA_VANTAGE_API_KEY=J7HIEITLQ515FHNS
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
      - FLASK_RUN_EXTRA_FILES=*.py
    volumes:
      - ./backend:/app
    networks:
      - optiq-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend/stock-charts-app
      dockerfile: Dockerfile
    container_name: terminal-frontend
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/stock-charts-app:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - optiq-network
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - BROWSER=none

networks:
  optiq-network:
    driver: bridge 